version: "3"
services:
  auth-service:
    build:
      context: ./AuthService
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - MONGODB_URL=mongodb://mongo:27017/auth
      - AUTH_SERVICE_URL=http://localhost:8001

  user-service:
    build:
      context: ./UserService
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - MONGODB_URL=mongodb://mongo:27017/user
      - USER_SERVICE_URL=http://localhost:8002

  product-service:
    build:
      context: ./ProductService
    ports:
      - "8003:8003"
    environment:
      - PORT=8003
      - MONGODB_URL=mongodb://mongo:27017/product
      - PRODUCT_SERVICE_URL=http://localhost:8003

  address-service:
    build:
      context: ./AddressService
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
      - MONGODB_URL=mongodb://mongo:27017/address
      - ADDRESS_SERVICE_URL=http://localhost:8004

  review-service:
    build:
      context: ./ReviewService
    ports:
      - "8008:8008"
    environment:
      - PORT=8008
      - MONGODB_URL=mongodb://mongo:27017/review
      - REVIEW_SERVICE_URL=http://localhost:8008

  api-gateway:
    build:
      context: ./APIGateway
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AUTH_SERVICE_URL=http://auth-service:8001
      - USER_SERVICE_URL=http://user-service:8002
      - PRODUCT_SERVICE_URL=http://product-service:8003
      - ADDRESS_SERVICE_URL=http://address-service:8004
      - REVIEW_SERVICE_URL=http://review-service:8008

  mongo:
    image: mongo
    ports:
      - "27017:27017"
