services:
  auth-service:
    container_name: auth-service
    build:
      context: ./AuthService
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - MONGODB_URL=mongodb+srv://mongobasic:hellohm11@cluster0.dbvpcq4.mongodb.net/greenveggies?retryWrites=true&w=majority&appName=Cluster0
      - AUTH_SERVICE_URL=http://localhost:8001

  user-service:
    container_name: user-service
    build:
      context: ./UserService
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - MONGODB_URL=mongodb+srv://mongobasic:hellohm11@cluster0.dbvpcq4.mongodb.net/greenveggies?retryWrites=true&w=majority&appName=Cluster0
      - USER_SERVICE_URL=http://localhost:8002

  product-service:
    container_name: product-service
    build:
      context: ./ProductService
    ports:
      - "8003:8003"
    volumes:
      - ./ProductService:/app
    environment:
      - PORT=8003
      - MONGODB_URL=mongodb+srv://mongobasic:hellohm11@cluster0.dbvpcq4.mongodb.net/greenveggies?retryWrites=true&w=majority&appName=Cluster0
      - PRODUCT_SERVICE_URL=http://localhost:8003

  address-service:
    container_name: address-service
    build:
      context: ./AddressService
    ports:
      - "8004:8004"
    environment:
      - PORT=8004
      - MONGODB_URL=mongodb+srv://mongobasic:hellohm11@cluster0.dbvpcq4.mongodb.net/greenveggies?retryWrites=true&w=majority&appName=Cluster0
      - ADDRESS_SERVICE_URL=http://localhost:8004

  order-service:
    container_name: order-service
    build:
      context: ./OrderService
    ports:
      - "8005:8005"
    environment:
      - PORT=8005
      - MONGODB_URL=mongodb+srv://mongobasic:hellohm11@cluster0.dbvpcq4.mongodb.net/greenveggies?retryWrites=true&w=majority&appName=Cluster0
      - ORDER_SERVICE_URL=http://localhost:8005

  review-service:
    container_name: review-service
    build:
      context: ./ReviewService
    ports:
      - "8008:8008"
    environment:
      - PORT=8008
      - MONGODB_URL=mongodb+srv://mongobasic:hellohm11@cluster0.dbvpcq4.mongodb.net/greenveggies?retryWrites=true&w=majority&appName=Cluster0
      - REVIEW_SERVICE_URL=http://localhost:8008

  api-gateway:
    container_name: api-gateway
    build:
      context: ./APIGateway
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AUTH_SERVICE_URL=http://auth-service:8001
      - USER_SERVICE_URL=http://user-service:8002
      - PRODUCT_SERVICE_URL=http://product-service:8003
      - ADDRESS_SERVICE_URL=http://address-service:8004
      - ORDER_SERVICE_URL=http://order-service:8005
      - REVIEW_SERVICE_URL=http://review-service:8008

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
